### ISSUE TITLE
Live reload

### ISSUE THREAD

**Issue by CMCDragonkai** [75lb/live-reload#1]
When I try to run this `--stack live-reload` option, it gives:

```
UNKNOWN_OPTION: Unknown option: --log.format
    at commandLineArgs (/home/cmcdragonkai/Projects/react-experiments/node_modules/command-line-args/index.js:59:21)                              
    at WsServe.getOptions (/home/cmcdragonkai/Projects/react-experiments/node_modules/lws/lib/command/serve.js:254:18)                            
    at WsServe.execute (/home/cmcdragonkai/Projects/react-experiments/node_modules/lws/lib/command/serve.js:265:20)                               
    at WsServe.execute (/home/cmcdragonkai/Projects/react-experiments/node_modules/local-web-server/lib/command/serve.js:16:18)                   
    at Map.start (/home/cmcdragonkai/Projects/react-experiments/node_modules/cli-commands/index.js:26:18)                                         
    at WsCliApp.start (/home/cmcdragonkai/Projects/react-experiments/node_modules/lws/lib/cli-app.js:11:34)                                       
    at Function.run (/home/cmcdragonkai/Projects/react-experiments/node_modules/lws/lib/cli-app.js:23:21)                                         
    at Object.<anonymous> (/home/cmcdragonkai/Projects/react-experiments/node_modules/local-web-server/bin/cli.js:12:29)                          
    at Module._compile (module.js:624:30)                                
    at Object.Module._extensions..js (module.js:635:10)
```

The total command is: `ws --log.format tiny --directory public --spa index.html --stack live-reload`

**Comment by 75lb** [comment]
yes, that's correct behaviour. `--log.format` is an option for the lws-log middleware, which is not loaded if you set a custom stack of `--stack live-reload`. 

If you run this command, you'll see the stack which is included by default. 

```
$ $ ws --config
{ port: 8000,
  stack:
   Stack [
     BasicAuth,
     BodyParser,
     RequestMonitor,
     Log,
     Cors,
     Json,
     Compress,
     Rewrite,
     Blacklist,
     ConditionalGet,
     Mime,
     Cors,
     MockResponse,
     SPA,
     Static,
     Index ],
  directory: 'public',
  spa: 'index.html',
  view: CliView { options: undefined, events: [] } }
```

Now, if you run `ws --help` you'll see the `--log.format` option in the usage guide because the `lws-log` middleware is loaded (by default). If you run the following command, passing a stack which only includes `lws-log` you'll not see `--log.format` as it is not loaded.

```
$ ws --stack live-reload --help

local-web-server

  The modular web server for productive full-stack development.

Synopsis

  $ ws <options>
  $ ws command <options>

Server Options

  Options set on the server.

  --port, -p number             Web server port.
  --hostname string             The hostname (or IP address) to listen on. Defaults to 0.0.0.0 (any host).
  --max-connections number      The maximum number of concurrent connections supported by the server.
  --keep-alive-timeout number   The period (in milliseconds) of inactivity a connection will remain open
                                before being destroyed. Set to `0` to keep connections open indefinitely.

  HTTPS/TLS specific options.

  --https                    Enable HTTPS using a built-in TLS certificate registered to the hosts
                             127.0.0.1 and localhost.
  --key file                 Private key. Supply along with --cert to launch a https server.
  --cert file                Certificate chain. Supply along with --key to launch a https server.
  --pfx file                 Optional PFX or PKCS12 encoded private key and certificate chain. An
                             alternative to providing --key and --cert.
  --ciphers string           Optional cipher suite specification, replacing the default.
  --secure-protocol string   Optional SSL method to use, default is "SSLv23_method".

Extension Options

  --stack path ...   Construct a middleware stack using the modules provided.
  --server path      Custom server factory, e.g. lws-http2
  --websocket path   A path to a websocket module
  --view path        A path to a custom view module

Middleware stack

  ↓ LiveReload   Adds live-reload support.

Middleware options

  --live-reload.port number   Port for live-reload server to listen on.
  --live-reload.excludes      One or more paths to be excluded from injection (e.g. Angular partials/views)

View options

  --verbose, -v        Outputs a highly verbose JSON stream containing debug information. Intended
                       as a datasource for custom views.
  --verbose.include    One or more regular expressions describing which event keys to include in
                       verbose output. Implies --verbose.
  --verbose.exclude    One or more regular expressions describing which event keys to exclude from
                       verbose output. Implies --verbose.

Misc Options

  --help, -h               Print these usage instructions.
  --version                Print the version number.
  --config-file, -c file   Config filename to use, defaults to "lws.config.js".
  --config                 Print the active config.

Commands

  middleware-list   Print available middleware

  Project home: https://github.com/lwsjs/local-web-server
```

Try passing a stack which includes `lws-log`. 

```
$ ws --stack live-reload log
```

**Comment by CMCDragonkai** [comment]
Is there a way to append live reload to the default stack?

**Comment by 75lb** [comment]
no, because that wouldn't work.. the final middleware in the current stack is lws-static which constructs a response - a middleware placed after that one might not have the desired effect if the response is already written. 

Order is significant and the `--stack` option adds middleware in the order supplied.. so, you'd need to specify `--stack` with live-reload placed near the start, i imagine.
